### ISSUE TITLE
the speed of downloading the pretrained model is too slow, would you mind to upload the pretrained model to the google driver?

### ISSUE THREAD

**Issue by ShihuaiXu** [atapour/temporal-depth-segmentation#1]
thanks for your great work, would you mind to upload the pretrained model to the google driver?
https://collections.durham.ac.uk/downloads/r25425k9734

**Comment by atapour** [comment]
Thank you for the interest in the work.

I believe the speed issue might have been temporary as I just downloaded the model at 4 MB/s.

However, I have made the weights available on google drive as well. Hope this solves the issue.

Link: https://drive.google.com/file/d/1GL0nedEfh1KxHiwprkvBHxs8guhE-iJt/view?usp=sharing

**Comment by ShihuaiXu** [comment]
thank you very much
